version: '2'
services:
  ctfd:
    image: james9074/ctfd:1.0.6
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - SECRET_KEY=74y9w8uojtuh8t
      - LOG_FOLDER=/var/log/CTFd
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=4
    volumes:
      - /data/ctf/CTFd/logs:/var/log/CTFd
      - /data/ctf/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
  db:
    image: mariadb:10.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - /data/ctf/mysql:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
  cache:
    image: redis:4
    restart: always
    volumes:
    - /data/ctf/redis:/data